[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

reqwest = { version = "0.12.23", features = ["json"] }

reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
schemars = "0.8"
jsonschema = "0.16"
jsonschema = "0.16"

# Per-IP rate limiting middleware for Tower/Axum
tower-governor = { version = "0.5", default-features = false, features = ["axum"] }

